# Generated by Django 5.2.3 on 2025-06-26 15:54

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Firmenname')),
                ('tax_id', models.CharField(max_length=50, verbose_name='Steuernummer')),
                ('vat_id', models.CharField(blank=True, max_length=50, verbose_name='USt-IdNr.')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Unternehmen',
                'verbose_name_plural': 'Unternehmen',
                'db_table': 'companies',
            },
        ),
    ]
